### ISSUE TITLE
New release checklist

### ISSUE THREAD

**Issue by kirbyfan64** [felix-lang/fbuild#30]
Fbuild hasn't had a release in years. It's time for that to change!!

- [ ] Make sure MinGW works again.
- [ ] Clean up the flags vs cflags vs lflags debacle.
- [ ] Add the ability to add flags to a C/C++ builders after it's been guessed.
- [ ] Improve installation support.
- [ ] Create binary variants (Nuitka? PyInstaller?) and probably a portable, single-file Python script (a.l.a. pfbuild).
- [ ] More docs!
- [ ] ...

**Comment by kirbyfan64** [comment]
Improved install done in 90d653a.
